### ISSUE TITLE
example run failed

### ISSUE THREAD

**Issue by xuruijing** [ipfs/js-ipfsd-ctl#244]
I use command "npm install --save ipfsd-ctl" and "npm i ipfs", then run a example. 
$ node local-disposable.js

/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/utils/find-ipfs-executable.js:34
  throw new Error('Cannot find the IPFS executable')
  ^

Error: Cannot find the IPFS executable
    at module.exports (/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/utils/find-ipfs-executable.js:34:9)
    at new Daemon (/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/ipfsd-daemon.js:67:46)
    at FactoryDaemon.spawn (/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/factory-daemon.js:132:18)
    at Object.<anonymous> (/Users/xuruijing/Downloads/js-ipfsd-ctl-master/examples/local-disposable/local-disposable.js:14:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by vasco-santos** [comment]
Hello @xuruijing 

Thanks for reaching out with this issue. I went to `js-ipfsd-ctl` master branch and did exactly as you mentioned:

- `$ cd examples/local-disposable`
- `$ npm install ipfsd-ctl`
- `$ npm install ipfs`
- `$ node local-disposable.js`

After this, I got an error different from yours:

```
/Users/vsantos/Work/repos/js-ipfsd-ctl/examples/local-disposable/local-disposable.js:53
      throw err
      ^

Error: invalid block
    at setImmediate (/Users/vsantos/Work/repos/js-ipfsd-ctl/node_modules/ipfs-repo/src/blockstore.js:90:20)
    at Immediate._onImmediate (/Users/vsantos/Work/repos/js-ipfsd-ctl/node_modules/async/internal/setImmediate.js:27:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

This error is already fixed, but the new version is not released yet. Accordingly, if you clone `js-ipfs` and link the current master implementation of `js-ipfs` in this example, you will be able to run `local-disposable.js` correctly.

I tried this using `Node v8.9.4`. If you can give me more information to replicate your problem, I will be available for helping you.

**Comment by xuruijing** [comment]
I tried again according to the above steps, the problem is still, I'm using version of node 8.11.1. I saw "node_modules" under "locale-disposable", and there was ipfs in it, so I don't know why it couldn't find ipfs?

**Comment by vasco-santos** [comment]
Well, I changed my node version to 8.11.1 as well, and I can run the example as well. Did you link the master implementation of `js-ipfs`?

**Comment by xuruijing** [comment]
yes. What more detailed information do I need to provide? I upload my directory structure.
![1525947786319](https://user-images.githubusercontent.com/15903078/39865483-9f94dcd6-547f-11e8-9e5d-c2d7e29b5149.jpg)

**Comment by fsdiogo** [comment]
Hey @xuruijing, you probably didn't `npm i` in the root directory, that's why IPFS can't be found.

Follow these steps:

1. Go to the root of the `ipfsd-ctl` and run `npm i`
2. Go to `examples/local-disposable` and run `npm i`
3. Clone the `js-ipfs` repo
4. Go to the root of `js-ipfs` and run `npm link`
5. Go to `examples/local-disposable` and run `npm link ipfs`
6. Run `node local-disposable.js`

**Comment by xuruijing** [comment]
Go to the root of the ipfsd-ctl and run npm I

![1122](https://user-images.githubusercontent.com/15903078/39867195-54381ab2-5486-11e8-8d89-8bb52a767a5b.png)

**Comment by xuruijing** [comment]
I clone a fresh ipfsd-ctl repo, Go to the root of the ipfsd-ctl and run npm I, the problem is still.

![2018-05-11 10 48 41](https://user-images.githubusercontent.com/15903078/39904107-eec3ad1c-5508-11e8-8cef-d363775c6b5b.png)

**Comment by xuruijing** [comment]
> bogon:local-disposable xuruijing$ npm link ipfs

/Users/xuruijing/Downloads/js-ipfsd-ctl-master/examples/local-disposable/node_modules/ipfs -> /Users/xuruijing/.nvm/versions/node/v8.11.1/lib/node_modules/ipfs -> /Users/xuruijing/Downloads/js-ipfs-master

> bogon:local-disposable xuruijing$ node local-disposable.js 

/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/utils/find-ipfs-executable.js:34
  throw new Error('Cannot find the IPFS executable')
  ^

Error: Cannot find the IPFS executable
    at module.exports (/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/utils/find-ipfs-executable.js:34:9)
    at new Daemon (/Users/xuruijing/Downloads/js-ipfsd-ctl-master/src/ipfsd-daemon.js:67:46)

**Comment by vasco-santos** [comment]
So @xuruijing the `npm i` command is not working correctly right? Is [this](https://github.com/ipfs/js-ipfsd-ctl/issues/244#issuecomment-388244340) log from `npm i`?

Basically, the problem is with the `go node`. The example does not find the `go-ipfs-dep`.

**Comment by dryajov** [comment]
Note: I'm not claiming its failing because of that (or even that it is blocked), but the fact that it fails to download might indicate some network failure or a blockage.

**Comment by xuruijing** [comment]
I am in China, so it is possible that some modules are blocked. I tried this to see if I could run the ipfs node on IOS (mainly gateways), and I haven't succeeded yet.

**Comment by vasco-santos** [comment]
Can you test this behind a VPN / Proxy, in order to identify if that is really the problem?

**Comment by xuruijing** [comment]
I've been using a VPN, and I don't know why some blocked addresses are still inaccessible.

**Comment by xuruijing** [comment]
I delete go-ipfs-dep, only use js-ipfs, example of local-disposable is ok. Thank you for your help. There is a question, does this project launch the ipfs daemon, including the gateway? If include, how get the gateway address.like ` ipfsd.api.id` in examples. @vasco-santos @dryajov
